### ISSUE TITLE
error: no match for ‘operator/=’ (operand types are ‘cv::Point3d {aka cv::Point3_<double>}’ and ‘double’)

### ISSUE THREAD

**Issue by hxn135** [ivision-ufba/depth-face-detection#6]
When I build code, I get this issue.
Anyone has overcame it, plz give me an instruction!!! Thankiu in advance

**Comment by gdahia** [comment]
Hi, can you tell me the version of your OpenCV installation?

**Comment by hxn135** [comment]
I installed OpenCV 2.4.11

**Comment by gdahia** [comment]
Can you try it with OpenCV 3? Ideally, OpenCV 3.2.0

**Comment by gdahia** [comment]
Closed due to inactivity
